package com.uni.service.use.repository;

import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import com.uni.framework.crud.base.BaseRepository;

import com.uni.service.use.entity.UseRorg;

/**
 * repository for UseRorg generated by jpa-codegen
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-08-26.
 */
@RepositoryRestResource(path = "useRorg", itemResourceRel = "resource", collectionResourceRel = "resources")
public interface UseRorgRepository extends BaseRepository<UseRorg, Long> {


}
