package com.uni.service.user.service;

import java.util.List;
import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.Sort.Direction;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.uni.framework.crud.base.dto.BaseSearchDto;
import com.uni.framework.crud.base.BaseService;
import com.uni.framework.crud.base.utils.PageInfo;
import com.uni.service.user.entity.UserSign;
import com.uni.service.user.dto.request.UserSignRequestDto;
import com.uni.service.user.dto.response.UserSignResponseDto;
import com.uni.service.user.dto.search.UserSignSearchDto;

import lombok.extern.slf4j.Slf4j;

/**
 * service for UserSign generated by jpa-codegen
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-10-04.
 */
@Slf4j
@Service
@Transactional(readOnly = true)
public class UserSignService extends BaseService<UserSign, Long> {

    //@Autowired
    //private UserSignRepository userSignRepository;

    /**
     * 创建实体
     *
     * @param userSignRequestDto 表单
     * @return 实体对象
     */
    @Transactional(readOnly = false)
    public UserSignResponseDto create(UserSignRequestDto userSignRequestDto) {
        UserSign userSign = new UserSign();
        super.mapper(userSign, userSignRequestDto);
        userSign = super.save(userSign);
        return super.mapperByClass(userSign, UserSignResponseDto.class);
    }

    /**
     * 删除实体
     * @param id 实体id
     */
    @Override
    @Transactional(readOnly = false)
    public void deleteById(Long id) {
        super.findById(id).ifPresent(t -> {
            t.setIsActive(Boolean.FALSE);
            super.save(t);
        });
    }

    /**
     * 根据主键集合批量删除
     *
     * @param ids
     */
    @Transactional(readOnly = false)
    public void deleteByIds(List<Long> ids) {
        super.deleteAllById(ids);
    }

    /**
     * 更新实体
     *
     * @param dto 表单
     * @param id      实体id
     * @return 实体对象
     */
    @Transactional(readOnly = false)
    public UserSignResponseDto update(Long id, UserSignRequestDto userSignRequestDto) {
        UserSign userSign = super.findById(id).get();
        super.mapper(userSign, userSignRequestDto);
        userSign = super.save(userSign);
        return super.mapperByClass(userSign, UserSignResponseDto.class);
    }

    /**
     * 获取一个实体对象
     *
     * @param id 实体id
     * @return 实体对象
     */
    public UserSignResponseDto details(Long id) {
        UserSign userSign = super.findById(id).get();
        return super.mapperByClass(userSign, UserSignResponseDto.class);
    }

    /**
     * 分页列表
     *
     * @param searchParams 搜索参数
     * @param pageInfo     分页信息
     * @return 分页列表
     */
    public Page<UserSignResponseDto> getPageList(Map<String, Object> searchParams, PageInfo pageInfo) {
        BaseSearchDto searchDto = super.conver(searchParams, UserSignSearchDto.class);
        Map<String, Object> searchMap = searchDto.getSearchParams();
        log.debug("UserSign的分页搜索的条件是={},排序的字段为={}", searchMap, pageInfo.getSortType());
        Page<UserSign> page = super.findPageBySort(searchMap, pageInfo.getNumber(), pageInfo.getSize(), Direction.DESC,
                pageInfo.getSortType().split(","));
        Page<UserSignResponseDto> respPage = new PageImpl<>(super.mapperList(page.getContent(), UserSignResponseDto.class),
                page.getPageable(), page.getTotalElements());
        return respPage;
    }

    /**
     * 根据搜索条件搜索所有符合条件的信息列表
     *
     * @param searchParams 搜索参数
     * @return 信息列表
     */
    public List<UserSignResponseDto> findByParams(Map<String, Object> searchParams, String sortTypes) {
        BaseSearchDto searchDto = super.conver(searchParams, UserSignSearchDto.class);
        log.debug("UserSign的不分页搜索的参数是={}", searchDto);
        List<UserSign> list = super.findAllBySort(searchDto.getSearchParams(), Direction.DESC, sortTypes.split(","));
        return super.mapperList(list, UserSignResponseDto.class);
    }

}
