package com.uni.service.user.service;

import java.util.List;
import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.Sort.Direction;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.uni.framework.crud.base.dto.BaseSearchDto;
import com.uni.framework.crud.base.BaseService;
import com.uni.framework.crud.base.utils.PageInfo;
import com.uni.service.user.entity.UserAddress;
import com.uni.service.user.dto.request.UserAddressRequestDto;
import com.uni.service.user.dto.response.UserAddressResponseDto;
import com.uni.service.user.dto.search.UserAddressSearchDto;

import lombok.extern.slf4j.Slf4j;

/**
 * service for UserAddress generated by jpa-codegen
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-10-04.
 */
@Slf4j
@Service
@Transactional(readOnly = true)
public class UserAddressService extends BaseService<UserAddress, Long> {

    //@Autowired
    //private UserAddressRepository userAddressRepository;

    /**
     * 创建实体
     *
     * @param userAddressRequestDto 表单
     * @return 实体对象
     */
    @Transactional(readOnly = false)
    public UserAddressResponseDto create(UserAddressRequestDto userAddressRequestDto) {
        UserAddress userAddress = new UserAddress();
        super.mapper(userAddress, userAddressRequestDto);
        userAddress = super.save(userAddress);
        return super.mapperByClass(userAddress, UserAddressResponseDto.class);
    }

    /**
     * 删除实体
     * @param id 实体id
     */
    @Override
    @Transactional(readOnly = false)
    public void deleteById(Long id) {
        super.findById(id).ifPresent(t -> {
            t.setIsActive(Boolean.FALSE);
            super.save(t);
        });
    }

    /**
     * 根据主键集合批量删除
     *
     * @param ids
     */
    @Transactional(readOnly = false)
    public void deleteByIds(List<Long> ids) {
        super.deleteAllById(ids);
    }

    /**
     * 更新实体
     *
     * @param dto 表单
     * @param id      实体id
     * @return 实体对象
     */
    @Transactional(readOnly = false)
    public UserAddressResponseDto update(Long id, UserAddressRequestDto userAddressRequestDto) {
        UserAddress userAddress = super.findById(id).get();
        super.mapper(userAddress, userAddressRequestDto);
        userAddress = super.save(userAddress);
        return super.mapperByClass(userAddress, UserAddressResponseDto.class);
    }

    /**
     * 获取一个实体对象
     *
     * @param id 实体id
     * @return 实体对象
     */
    public UserAddressResponseDto details(Long id) {
        UserAddress userAddress = super.findById(id).get();
        return super.mapperByClass(userAddress, UserAddressResponseDto.class);
    }

    /**
     * 分页列表
     *
     * @param searchParams 搜索参数
     * @param pageInfo     分页信息
     * @return 分页列表
     */
    public Page<UserAddressResponseDto> getPageList(Map<String, Object> searchParams, PageInfo pageInfo) {
        BaseSearchDto searchDto = super.conver(searchParams, UserAddressSearchDto.class);
        Map<String, Object> searchMap = searchDto.getSearchParams();
        log.debug("UserAddress的分页搜索的条件是={},排序的字段为={}", searchMap, pageInfo.getSortType());
        Page<UserAddress> page = super.findPageBySort(searchMap, pageInfo.getNumber(), pageInfo.getSize(), Direction.DESC,
                pageInfo.getSortType().split(","));
        Page<UserAddressResponseDto> respPage = new PageImpl<>(super.mapperList(page.getContent(), UserAddressResponseDto.class),
                page.getPageable(), page.getTotalElements());
        return respPage;
    }

    /**
     * 根据搜索条件搜索所有符合条件的信息列表
     *
     * @param searchParams 搜索参数
     * @return 信息列表
     */
    public List<UserAddressResponseDto> findByParams(Map<String, Object> searchParams, String sortTypes) {
        BaseSearchDto searchDto = super.conver(searchParams, UserAddressSearchDto.class);
        log.debug("UserAddress的不分页搜索的参数是={}", searchDto);
        List<UserAddress> list = super.findAllBySort(searchDto.getSearchParams(), Direction.DESC, sortTypes.split(","));
        return super.mapperList(list, UserAddressResponseDto.class);
    }

}
