package com.uni.service.t.dto.search;

import java.util.Map;

import com.uni.framework.crud.base.dto.BaseSearchDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import java.time.LocalDateTime;

/**
 *  TAdvertisement Dto generated by auto
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-08-26.
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class TAdvertisementSearchDto extends BaseSearchDto{


    /**
     * TODO 字段信息描述
     */
    private Integer advertisementId;

    /**
     * TODO 字段信息描述
     */
    private String userId;

    /**
     * TODO 字段信息描述
     */
    private String creatorId;

    /**
     * TODO 字段信息描述
     */
    private String advertisementImg;

    /**
     * TODO 字段信息描述
     */
    private String advertisementUrl;

    /**
     * TODO 字段信息描述
     */
    private Integer clicksCount;

    /**
     * TODO 字段信息描述
     */
    private LocalDateTime createTime;

    /**
     * TODO 字段信息描述
     */
    private LocalDateTime updateTime;

    /**
     * 实现父类的查询条件过滤
     *
     */
    @Override
    public void buildSearchParams(Map<String, Object> map) {
        super.putNoNull("EQ_advertisementId", this.advertisementId, map);
        super.putNoNull("EQ_userId", this.userId, map);
        super.putNoNull("EQ_creatorId", this.creatorId, map);
        super.putNoNull("EQ_advertisementImg", this.advertisementImg, map);
        super.putNoNull("EQ_advertisementUrl", this.advertisementUrl, map);
        super.putNoNull("EQ_clicksCount", this.clicksCount, map);
        super.putNoNull("EQ_createTime", this.createTime, map);
        super.putNoNull("EQ_updateTime", this.updateTime, map);
    }

}
