package com.uni.service.t.dto.search;

import java.util.Map;

import com.uni.framework.crud.base.dto.BaseSearchDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import java.time.LocalDateTime;

/**
 *  TComment Dto generated by auto
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-08-26.
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class TCommentSearchDto extends BaseSearchDto{


    /**
     * TODO 字段信息描述
     */
    private Integer commentId;

    /**
     * TODO 字段信息描述
     */
    private String userId;

    /**
     * TODO 字段信息描述
     */
    private Integer commentParentId;

    /**
     * TODO 字段信息描述
     */
    private String commentContent;

    /**
     * TODO 字段信息描述
     */
    private Integer commentState;

    /**
     * TODO 字段信息描述
     */
    private Integer newsId;

    /**
     * TODO 字段信息描述
     */
    private LocalDateTime createTime;

    /**
     * 实现父类的查询条件过滤
     *
     */
    @Override
    public void buildSearchParams(Map<String, Object> map) {
        super.putNoNull("EQ_commentId", this.commentId, map);
        super.putNoNull("EQ_userId", this.userId, map);
        super.putNoNull("EQ_commentParentId", this.commentParentId, map);
        super.putNoNull("EQ_commentContent", this.commentContent, map);
        super.putNoNull("EQ_commentState", this.commentState, map);
        super.putNoNull("EQ_newsId", this.newsId, map);
        super.putNoNull("EQ_createTime", this.createTime, map);
    }

}
