package com.uni.service.t.dto.search;

import java.util.Map;

import com.uni.framework.crud.base.dto.BaseSearchDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import java.time.LocalDateTime;

/**
 *  THotspots Dto generated by auto
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-08-26.
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class THotspotsSearchDto extends BaseSearchDto{


    /**
     * TODO 字段信息描述
     */
    private Integer hotspotsId;

    /**
     * TODO 字段信息描述
     */
    private Integer newsId;

    /**
     * TODO 字段信息描述
     */
    private String newsScore;

    /**
     * TODO 字段信息描述
     */
    private LocalDateTime newsPublishtime;

    /**
     * TODO 字段信息描述
     */
    private LocalDateTime updateTime;

    /**
     * 实现父类的查询条件过滤
     *
     */
    @Override
    public void buildSearchParams(Map<String, Object> map) {
        super.putNoNull("EQ_hotspotsId", this.hotspotsId, map);
        super.putNoNull("EQ_newsId", this.newsId, map);
        super.putNoNull("EQ_newsScore", this.newsScore, map);
        super.putNoNull("EQ_newsPublishtime", this.newsPublishtime, map);
        super.putNoNull("EQ_updateTime", this.updateTime, map);
    }

}
