package com.uni.service.t.repository;

import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import com.uni.framework.crud.base.BaseRepository;

import com.uni.service.t.entity.TComment;

/**
 * repository for TComment generated by jpa-codegen
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-08-26.
 */
@RepositoryRestResource(path = "tComment", itemResourceRel = "resource", collectionResourceRel = "resources")
public interface TCommentRepository extends BaseRepository<TComment, Long> {


}
