package com.uni.service.user.dto.search;

import java.util.Map;

import com.uni.framework.crud.base.dto.BaseSearchDto;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 *  UserOrg Dto generated by auto
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-09-17.
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class UserOrgSearchDto extends BaseSearchDto{


    /**
     * TODO 字段信息描述
     */
    private String uid;

    /**
     * TODO 字段信息描述
     */
    private String groupId;

    /**
     * TODO 字段信息描述
     */
    private String postId;

    /**
     * TODO 字段信息描述
     */
    private String groupName;

    /**
     * TODO 字段信息描述
     */
    private String postName;

    /**
     * 实现父类的查询条件过滤
     *
     */
    @Override
    public void buildSearchParams(Map<String, Object> map) {
        super.putNoNull("EQ_uid", this.uid, map);
        super.putNoNull("EQ_groupId", this.groupId, map);
        super.putNoNull("EQ_postId", this.postId, map);
        super.putNoNull("EQ_groupName", this.groupName, map);
        super.putNoNull("EQ_postName", this.postName, map);
    }

}
