package com.uni.service.user.dto.search;

import java.util.Map;

import com.uni.framework.crud.base.dto.BaseSearchDto;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 *  UserAddress Dto generated by auto
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-09-17.
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class UserAddressSearchDto extends BaseSearchDto{


    /**
     * TODO 字段信息描述
     */
    private String uid;

    /**
     * TODO 字段信息描述
     */
    private String province;

    /**
     * TODO 字段信息描述
     */
    private String city;

    /**
     * TODO 字段信息描述
     */
    private String district;

    /**
     * TODO 字段信息描述
     */
    private String street;

    /**
     * TODO 字段信息描述
     */
    private Integer typ;

    /**
     * TODO 字段信息描述
     */
    private Integer indx;

    /**
     * TODO 字段信息描述
     */
    private String contacts;

    /**
     * TODO 字段信息描述
     */
    private String phoneNum;

    /**
     * 实现父类的查询条件过滤
     *
     */
    @Override
    public void buildSearchParams(Map<String, Object> map) {
        super.putNoNull("EQ_uid", this.uid, map);
        super.putNoNull("EQ_province", this.province, map);
        super.putNoNull("EQ_city", this.city, map);
        super.putNoNull("EQ_district", this.district, map);
        super.putNoNull("EQ_street", this.street, map);
        super.putNoNull("EQ_typ", this.typ, map);
        super.putNoNull("EQ_indx", this.indx, map);
        super.putNoNull("EQ_contacts", this.contacts, map);
        super.putNoNull("EQ_phoneNum", this.phoneNum, map);
    }

}
