package com.uni.service.rbac.dto.response;

import org.springframework.hateoas.server.core.Relation;

import com.uni.framework.crud.base.dto.BaseResponseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 *  RbacMenu generated by auto
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-10-04.
 */
@Data
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = false)
@Relation(collectionRelation = "resources")
public class RbacMenuResponseDto extends BaseResponseDto {

    private static final long serialVersionUID = -1L;

    /**
     * TODO 字段信息描述
     */
    private String pid;

    /**
     * TODO 字段信息描述
     */
    private String menuCode;

    /**
     * TODO 字段信息描述
     */
    private String menuName;

    /**
     * TODO 字段信息描述
     */
    private String menuVal;

    /**
     * TODO 字段信息描述
     */
    private Integer level;

    /**
     * TODO 字段信息描述
     */
    private Integer sorted;

    /**
     * TODO 字段信息描述
     */
    private Integer isFrame;

    /**
     * TODO 字段信息描述
     */
    private String icon;

}
