package com.uni.service.rbac.dto.response;

import org.springframework.hateoas.server.core.Relation;

import com.uni.framework.crud.base.dto.BaseResponseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 *  RbacResource generated by auto
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-10-04.
 */
@Data
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = false)
@Relation(collectionRelation = "resources")
public class RbacResourceResponseDto extends BaseResponseDto {

    private static final long serialVersionUID = -1L;

    /**
     * TODO 字段信息描述
     */
    private String categoryId;

    /**
     * TODO 字段信息描述
     */
    private String resourceName;

    /**
     * TODO 字段信息描述
     */
    private String resourceCode;

    /**
     * TODO 字段信息描述
     */
    private String resourceTyp;

    /**
     * TODO 字段信息描述
     */
    private String resourceVal;

    /**
     * TODO 字段信息描述
     */
    private String resourcePath;

    /**
     * TODO 字段信息描述
     */
    private String resourceIcon;

    /**
     * TODO 字段信息描述
     */
    private String resourceDescr;

    /**
     * TODO 字段信息描述
     */
    private Integer visible;

    /**
     * TODO 字段信息描述
     */
    private Integer level;

}
