package com.uni.service.rbac.dto.request;

import com.uni.framework.crud.base.dto.BaseRequestDto;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 *  RbacMenu Dto generated by auto
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-09-17.
 */
@Data
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = false)
public class RbacMenuRequestDto extends BaseRequestDto {

    /**
     *
     */
    private static final long serialVersionUID = -1L;

    /**
     * TODO 字段信息描述
     */
    private String pid;

    /**
     * TODO 字段信息描述
     */
    private String menuCode;

    /**
     * TODO 字段信息描述
     */
    private String menuName;

    /**
     * TODO 字段信息描述
     */
    private String menuVal;

    /**
     * TODO 字段信息描述
     */
    private Integer level;

    /**
     * TODO 字段信息描述
     */
    private Integer sorted;

    /**
     * TODO 字段信息描述
     */
    private Integer isFrame;

    /**
     * TODO 字段信息描述
     */
    private String icon;

}
