package com.uni.service.rbac.dto.request;

import com.uni.framework.crud.base.dto.BaseRequestDto;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 *  RbacPost Dto generated by auto
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-09-17.
 */
@Data
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = false)
public class RbacPostRequestDto extends BaseRequestDto {

    /**
     *
     */
    private static final long serialVersionUID = -1L;

    /**
     * TODO 字段信息描述
     */
    private String postPid;

    /**
     * TODO 字段信息描述
     */
    private String postName;

    /**
     * TODO 字段信息描述
     */
    private String postCode;

    /**
     * TODO 字段信息描述
     */
    private String postIcon;

    /**
     * TODO 字段信息描述
     */
    private String salary;

}
