package com.uni.service.rbac.dto.request;

import com.uni.framework.crud.base.dto.BaseRequestDto;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 *  RbacResource Dto generated by auto
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-09-17.
 */
@Data
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = false)
public class RbacResourceRequestDto extends BaseRequestDto {

    /**
     *
     */
    private static final long serialVersionUID = -1L;

    /**
     * TODO 字段信息描述
     */
    private String categoryId;

    /**
     * TODO 字段信息描述
     */
    private String resourceName;

    /**
     * TODO 字段信息描述
     */
    private String resourceCode;

    /**
     * TODO 字段信息描述
     */
    private String resourceTyp;

    /**
     * TODO 字段信息描述
     */
    private String resourceVal;

    /**
     * TODO 字段信息描述
     */
    private String resourcePath;

    /**
     * TODO 字段信息描述
     */
    private String resourceIcon;

    /**
     * TODO 字段信息描述
     */
    private String resourceDescr;

    /**
     * TODO 字段信息描述
     */
    private Integer visible;

    /**
     * TODO 字段信息描述
     */
    private Integer level;

}
