package com.uni.service.product.dto.search;

import java.util.Map;

import com.uni.framework.crud.base.dto.BaseSearchDto;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 *  ProductCategory Dto generated by auto
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-08-26.
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class ProductCategorySearchDto extends BaseSearchDto{


    /**
     * TODO 字段信息描述
     */
    private String categoryId;

    /**
     * TODO 字段信息描述
     */
    private Integer categoryPid;

    /**
     * TODO 字段信息描述
     */
    private Integer sort;

    /**
     * TODO 字段信息描述
     */
    private String url;

    /**
     * TODO 字段信息描述
     */
    private String icon;

    /**
     * TODO 字段信息描述
     */
    private String name;

    /**
     * TODO 字段信息描述
     */
    private Integer state;

    /**
     * TODO 字段信息描述
     */
    private String createTime;

    /**
     * 实现父类的查询条件过滤
     *
     */
    @Override
    public void buildSearchParams(Map<String, Object> map) {
        super.putNoNull("EQ_categoryId", this.categoryId, map);
        super.putNoNull("EQ_categoryPid", this.categoryPid, map);
        super.putNoNull("EQ_sort", this.sort, map);
        super.putNoNull("EQ_url", this.url, map);
        super.putNoNull("EQ_icon", this.icon, map);
        super.putNoNull("EQ_name", this.name, map);
        super.putNoNull("EQ_state", this.state, map);
        super.putNoNull("EQ_createTime", this.createTime, map);
    }

}
