package com.uni.service.user.dto.response;

import org.springframework.hateoas.server.core.Relation;

import com.uni.framework.crud.base.dto.BaseResponseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 *  UserIdcard generated by auto
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-10-04.
 */
@Data
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = false)
@Relation(collectionRelation = "resources")
public class UserIdcardResponseDto extends BaseResponseDto {

    private static final long serialVersionUID = -1L;

    /**
     * TODO 字段信息描述
     */
    private String uid;

    /**
     * TODO 字段信息描述
     */
    private String idcard;

    /**
     * TODO 字段信息描述
     */
    private String name;

    /**
     * TODO 字段信息描述
     */
    private Integer age;

    /**
     * TODO 字段信息描述
     */
    private Integer sex;

    /**
     * TODO 字段信息描述
     */
    private String birthday;

    /**
     * TODO 字段信息描述
     */
    private String nation;

    /**
     * TODO 字段信息描述
     */
    private String domicile;

    /**
     * TODO 字段信息描述
     */
    private String signOrg;

}
