package com.uni.service.cms.dto.request;

import com.uni.framework.crud.base.dto.BaseRequestDto;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import java.time.LocalDateTime;

/**
 *  CmsNews Dto generated by auto
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-08-26.
 */
@Data
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = false)
public class CmsNewsRequestDto extends BaseRequestDto {

    /**
     *
     */
    private static final long serialVersionUID = -1L;

    /**
     * TODO 字段信息描述
     */
    private Integer newsId;

    /**
     * TODO 字段信息描述
     */
    private String newsTitle;

    /**
     * TODO 字段信息描述
     */
    private String newsPic;

    /**
     * TODO 字段信息描述
     */
    private String newsContent;

    /**
     * TODO 字段信息描述
     */
    private LocalDateTime newsPublishtime;

    /**
     * TODO 字段信息描述
     */
    private Integer newsReadingnumber;

    /**
     * TODO 字段信息描述
     */
    private Integer newsCommentcount;

    /**
     * TODO 字段信息描述
     */
    private Integer categoryId;

    /**
     * TODO 字段信息描述
     */
    private String userId;

    /**
     * TODO 字段信息描述
     */
    private LocalDateTime updateTime;

}
