package com.uni.service.use.dto.search;

import java.util.Map;

import com.uni.framework.crud.base.dto.BaseSearchDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import java.time.LocalDateTime;

/**
 *  UseRorg Dto generated by auto
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-08-26.
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class UseRorgSearchDto extends BaseSearchDto{


    /**
     * TODO 字段信息描述
     */
    private String uid;

    /**
     * TODO 字段信息描述
     */
    private String groupid;

    /**
     * TODO 字段信息描述
     */
    private String postid;

    /**
     * TODO 字段信息描述
     */
    private String groupname;

    /**
     * TODO 字段信息描述
     */
    private String postname;

    /**
     * TODO 字段信息描述
     */
    private String appid;

    /**
     * TODO 字段信息描述
     */
    private String tenantid;

    /**
     * TODO 字段信息描述
     */
    private Integer isactive;

    /**
     * TODO 字段信息描述
     */
    private String createdby;

    /**
     * TODO 字段信息描述
     */
    private LocalDateTime createddate;

    /**
     * 实现父类的查询条件过滤
     *
     */
    @Override
    public void buildSearchParams(Map<String, Object> map) {
        super.putNoNull("EQ_uid", this.uid, map);
        super.putNoNull("EQ_groupid", this.groupid, map);
        super.putNoNull("EQ_postid", this.postid, map);
        super.putNoNull("EQ_groupname", this.groupname, map);
        super.putNoNull("EQ_postname", this.postname, map);
        super.putNoNull("EQ_appid", this.appid, map);
        super.putNoNull("EQ_tenantid", this.tenantid, map);
        super.putNoNull("EQ_isactive", this.isactive, map);
        super.putNoNull("EQ_createdby", this.createdby, map);
        super.putNoNull("EQ_createddate", this.createddate, map);
    }

}
