package com.uni.service.cms.dto.search;

import java.util.Map;

import com.uni.framework.crud.base.dto.BaseSearchDto;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 *  CmsArticle Dto generated by auto
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-08-26.
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class CmsArticleSearchDto extends BaseSearchDto{


    /**
     * TODO 字段信息描述
     */
    private String categoryId;

    /**
     * TODO 字段信息描述
     */
    private String articleId;

    /**
     * TODO 字段信息描述
     */
    private String groupId;

    /**
     * TODO 字段信息描述
     */
    private String accountId;

    /**
     * TODO 字段信息描述
     */
    private String groupName;

    /**
     * TODO 字段信息描述
     */
    private String accountName;

    /**
     * TODO 字段信息描述
     */
    private String title;

    /**
     * TODO 字段信息描述
     */
    private String summary;

    /**
     * TODO 字段信息描述
     */
    private String content;

    /**
     * TODO 字段信息描述
     */
    private String descr;

    /**
     * TODO 字段信息描述
     */
    private String href;

    /**
     * TODO 字段信息描述
     */
    private String pubtime;

    /**
     * TODO 字段信息描述
     */
    private Integer state;

    /**
     * TODO 字段信息描述
     */
    private String createTime;

    /**
     * 实现父类的查询条件过滤
     *
     */
    @Override
    public void buildSearchParams(Map<String, Object> map) {
        super.putNoNull("EQ_categoryId", this.categoryId, map);
        super.putNoNull("EQ_articleId", this.articleId, map);
        super.putNoNull("EQ_groupId", this.groupId, map);
        super.putNoNull("EQ_accountId", this.accountId, map);
        super.putNoNull("EQ_groupName", this.groupName, map);
        super.putNoNull("EQ_accountName", this.accountName, map);
        super.putNoNull("EQ_title", this.title, map);
        super.putNoNull("EQ_summary", this.summary, map);
        super.putNoNull("EQ_content", this.content, map);
        super.putNoNull("EQ_descr", this.descr, map);
        super.putNoNull("EQ_href", this.href, map);
        super.putNoNull("EQ_pubtime", this.pubtime, map);
        super.putNoNull("EQ_state", this.state, map);
        super.putNoNull("EQ_createTime", this.createTime, map);
    }

}
