package com.uni.service.cms.dto.search;

import java.util.Map;

import com.uni.framework.crud.base.dto.BaseSearchDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import java.time.LocalDateTime;

/**
 *  CmsNews Dto generated by auto
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-08-26.
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class CmsNewsSearchDto extends BaseSearchDto{


    /**
     * TODO 字段信息描述
     */
    private Integer newsId;

    /**
     * TODO 字段信息描述
     */
    private String newsTitle;

    /**
     * TODO 字段信息描述
     */
    private String newsPic;

    /**
     * TODO 字段信息描述
     */
    private String newsContent;

    /**
     * TODO 字段信息描述
     */
    private LocalDateTime newsPublishtime;

    /**
     * TODO 字段信息描述
     */
    private Integer newsReadingnumber;

    /**
     * TODO 字段信息描述
     */
    private Integer newsCommentcount;

    /**
     * TODO 字段信息描述
     */
    private Integer categoryId;

    /**
     * TODO 字段信息描述
     */
    private String userId;

    /**
     * TODO 字段信息描述
     */
    private LocalDateTime updateTime;

    /**
     * 实现父类的查询条件过滤
     *
     */
    @Override
    public void buildSearchParams(Map<String, Object> map) {
        super.putNoNull("EQ_newsId", this.newsId, map);
        super.putNoNull("EQ_newsTitle", this.newsTitle, map);
        super.putNoNull("EQ_newsPic", this.newsPic, map);
        super.putNoNull("EQ_newsContent", this.newsContent, map);
        super.putNoNull("EQ_newsPublishtime", this.newsPublishtime, map);
        super.putNoNull("EQ_newsReadingnumber", this.newsReadingnumber, map);
        super.putNoNull("EQ_newsCommentcount", this.newsCommentcount, map);
        super.putNoNull("EQ_categoryId", this.categoryId, map);
        super.putNoNull("EQ_userId", this.userId, map);
        super.putNoNull("EQ_updateTime", this.updateTime, map);
    }

}
