package com.uni.service.rbac.dto.search;

import java.util.Map;

import com.uni.framework.crud.base.dto.BaseSearchDto;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 *  RbacResource Dto generated by auto
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-10-04.
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class RbacResourceSearchDto extends BaseSearchDto{


    /**
     * TODO 字段信息描述
     */
    private String categoryId;

    /**
     * TODO 字段信息描述
     */
    private String resourceName;

    /**
     * TODO 字段信息描述
     */
    private String resourceCode;

    /**
     * TODO 字段信息描述
     */
    private String resourceTyp;

    /**
     * TODO 字段信息描述
     */
    private String resourceVal;

    /**
     * TODO 字段信息描述
     */
    private String resourcePath;

    /**
     * TODO 字段信息描述
     */
    private String resourceIcon;

    /**
     * TODO 字段信息描述
     */
    private String resourceDescr;

    /**
     * TODO 字段信息描述
     */
    private Integer visible;

    /**
     * TODO 字段信息描述
     */
    private Integer level;

    /**
     * 实现父类的查询条件过滤
     *
     */
    @Override
    public void buildSearchParams(Map<String, Object> map) {
        super.putNoNull("EQ_categoryId", this.categoryId, map);
        super.putNoNull("EQ_resourceName", this.resourceName, map);
        super.putNoNull("EQ_resourceCode", this.resourceCode, map);
        super.putNoNull("EQ_resourceTyp", this.resourceTyp, map);
        super.putNoNull("EQ_resourceVal", this.resourceVal, map);
        super.putNoNull("EQ_resourcePath", this.resourcePath, map);
        super.putNoNull("EQ_resourceIcon", this.resourceIcon, map);
        super.putNoNull("EQ_resourceDescr", this.resourceDescr, map);
        super.putNoNull("EQ_visible", this.visible, map);
        super.putNoNull("EQ_level", this.level, map);
    }

}
