package com.uni.service.rbac.dto.search;

import java.util.Map;

import com.uni.framework.crud.base.dto.BaseSearchDto;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 *  RbacMenu Dto generated by auto
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-10-04.
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class RbacMenuSearchDto extends BaseSearchDto{


    /**
     * TODO 字段信息描述
     */
    private String pid;

    /**
     * TODO 字段信息描述
     */
    private String menuCode;

    /**
     * TODO 字段信息描述
     */
    private String menuName;

    /**
     * TODO 字段信息描述
     */
    private String menuVal;

    /**
     * TODO 字段信息描述
     */
    private Integer level;

    /**
     * TODO 字段信息描述
     */
    private Integer sorted;

    /**
     * TODO 字段信息描述
     */
    private Integer isFrame;

    /**
     * TODO 字段信息描述
     */
    private String icon;

    /**
     * 实现父类的查询条件过滤
     *
     */
    @Override
    public void buildSearchParams(Map<String, Object> map) {
        super.putNoNull("EQ_pid", this.pid, map);
        super.putNoNull("EQ_menuCode", this.menuCode, map);
        super.putNoNull("EQ_menuName", this.menuName, map);
        super.putNoNull("EQ_menuVal", this.menuVal, map);
        super.putNoNull("EQ_level", this.level, map);
        super.putNoNull("EQ_sorted", this.sorted, map);
        super.putNoNull("EQ_isFrame", this.isFrame, map);
        super.putNoNull("EQ_icon", this.icon, map);
    }

}
