package com.uni.service.rbac.dto.search;

import java.util.Map;

import com.uni.framework.crud.base.dto.BaseSearchDto;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 *  RbacRole Dto generated by auto
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-10-04.
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class RbacRoleSearchDto extends BaseSearchDto{


    /**
     * TODO 字段信息描述
     */
    private String roleName;

    /**
     * TODO 字段信息描述
     */
    private String roleCode;

    /**
     * TODO 字段信息描述
     */
    private String icon;

    /**
     * TODO 字段信息描述
     */
    private String descr;

    /**
     * 实现父类的查询条件过滤
     *
     */
    @Override
    public void buildSearchParams(Map<String, Object> map) {
        super.putNoNull("EQ_roleName", this.roleName, map);
        super.putNoNull("EQ_roleCode", this.roleCode, map);
        super.putNoNull("EQ_icon", this.icon, map);
        super.putNoNull("EQ_descr", this.descr, map);
    }

}
