package com.uni.service.rbac.dto.search;

import java.util.Map;

import com.uni.framework.crud.base.dto.BaseSearchDto;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 *  RbacCategory Dto generated by auto
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-10-04.
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class RbacCategorySearchDto extends BaseSearchDto{


    /**
     * TODO 字段信息描述
     */
    private String pid;

    /**
     * TODO 字段信息描述
     */
    private String categoryName;

    /**
     * TODO 字段信息描述
     */
    private Integer sorted;

    /**
     * 实现父类的查询条件过滤
     *
     */
    @Override
    public void buildSearchParams(Map<String, Object> map) {
        super.putNoNull("EQ_pid", this.pid, map);
        super.putNoNull("EQ_categoryName", this.categoryName, map);
        super.putNoNull("EQ_sorted", this.sorted, map);
    }

}
