package com.uni.service.product.dto.request;

import com.uni.framework.crud.base.dto.BaseRequestDto;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 *  ProductCategory Dto generated by auto
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-08-26.
 */
@Data
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = false)
public class ProductCategoryRequestDto extends BaseRequestDto {

    /**
     *
     */
    private static final long serialVersionUID = -1L;

    /**
     * TODO 字段信息描述
     */
    private String categoryId;

    /**
     * TODO 字段信息描述
     */
    private Integer categoryPid;

    /**
     * TODO 字段信息描述
     */
    private Integer sort;

    /**
     * TODO 字段信息描述
     */
    private String url;

    /**
     * TODO 字段信息描述
     */
    private String icon;

    /**
     * TODO 字段信息描述
     */
    private String name;

    /**
     * TODO 字段信息描述
     */
    private Integer state;

    /**
     * TODO 字段信息描述
     */
    private String createTime;

}
