package com.uni.service.cms.repository;

import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import com.uni.framework.crud.base.BaseRepository;

import com.uni.service.cms.entity.CmsArticle;

/**
 * repository for CmsArticle generated by jpa-codegen
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-08-26.
 */
@RepositoryRestResource(path = "cmsArticle", itemResourceRel = "resource", collectionResourceRel = "resources")
public interface CmsArticleRepository extends BaseRepository<CmsArticle, Long> {


}
