package com.uni.service.cms.repository;

import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import com.uni.framework.crud.base.BaseRepository;

import com.uni.service.cms.entity.CmsNews;

/**
 * repository for CmsNews generated by jpa-codegen
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-08-26.
 */
@RepositoryRestResource(path = "cmsNews", itemResourceRel = "resource", collectionResourceRel = "resources")
public interface CmsNewsRepository extends BaseRepository<CmsNews, Long> {


}
