package com.uni.service.user.dto.request;

import com.uni.framework.crud.base.dto.BaseRequestDto;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 *  UserRelationship Dto generated by auto
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-09-17.
 */
@Data
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = false)
public class UserRelationshipRequestDto extends BaseRequestDto {

    /**
     *
     */
    private static final long serialVersionUID = -1L;

    /**
     * TODO 字段信息描述
     */
    private String pid;

    /**
     * TODO 字段信息描述
     */
    private Integer org;

    /**
     * TODO 字段信息描述
     */
    private Integer deep;

    /**
     * TODO 字段信息描述
     */
    private Integer seq;

    /**
     * TODO 字段信息描述
     */
    private String fromUid;

    /**
     * TODO 字段信息描述
     */
    private String fromUserName;

    /**
     * TODO 字段信息描述
     */
    private String fromUserPhone;

    /**
     * TODO 字段信息描述
     */
    private String toUid;

    /**
     * TODO 字段信息描述
     */
    private String toUserPhone;

    /**
     * TODO 字段信息描述
     */
    private String toUserName;

}
