package com.uni.service.rbac.repository;

import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import com.uni.framework.crud.base.BaseRepository;

import com.uni.service.rbac.entity.RbacResource;

/**
 * repository for RbacResource generated by jpa-codegen
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-09-17.
 */
@RepositoryRestResource(path = "rbacResource", itemResourceRel = "resource", collectionResourceRel = "resources")
public interface RbacResourceRepository extends BaseRepository<RbacResource, Long> {


}
