package com.uni.service.rbac.repository;

import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import com.uni.framework.crud.base.BaseRepository;

import com.uni.service.rbac.entity.RbacPost;

/**
 * repository for RbacPost generated by jpa-codegen
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-09-17.
 */
@RepositoryRestResource(path = "rbacPost", itemResourceRel = "resource", collectionResourceRel = "resources")
public interface RbacPostRepository extends BaseRepository<RbacPost, Long> {


}
