package com.uni.service.rbac.repository;

import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import com.uni.framework.crud.base.BaseRepository;

import com.uni.service.rbac.entity.RbacCategory;

/**
 * repository for RbacCategory generated by jpa-codegen
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-10-04.
 */
@RepositoryRestResource(path = "rbacCategory", itemResourceRel = "resource", collectionResourceRel = "resources")
public interface RbacCategoryRepository extends BaseRepository<RbacCategory, Long> {


}
