#server:
#  servlet:
#    context-path: /api
#spring:
#  data:
#    rest:
#      base-path: /rest
#  application:
#    name: test
#  jackson:
#    time-zone: GMT+8
#  jpa:
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:mysql://localhost:3306/rong_spring_test?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#uni:
#  author: lait
#  comments: 这是类的注释
#  cover: true
#  template:
#    dir: templates
#  base:
#    project:
#      #path:
#
#  dto:
#    package: com.uni.service.*.dto.request
#    template: dto.ftl
#    suffix: RequestDto
#  response:
#    package: com.uni.service.*.dto.response
#    template: response.ftl
#    suffix: ResponseDto
#  search:
#    package: com.uni.service.*.dto.search
#    template: search.ftl
#    suffix: SearchDto
#  controller:
#    package: com.uni.service.*.controller
#    template: controller.ftl
#    suffix: Controller
#  biz:
#    package: com.uni.service.*.biz
#    template: biz.ftl
#    suffix: Biz
#  service:
#    package: com.uni.service.*.service
#    template: service.ftl
#    suffix: Service
#
#  repository:
#    package: com.uni.service.*.repository
#    template: repository.ftl
#    suffix: Repository
#
#  entity:
#    package: com.uni.service.*.entity
#    template: entity.ftl
#    suffix:
#    id:
#      class: Long
#      package:
#
#  db:
#    driver: com.mysql.cj.jdbc.Driver
#    url: "jdbc:mysql://localhost:3306/uni?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai"
#    username: root
#    password: root
