package com.uni.service.cms.dto.response;

import org.springframework.hateoas.server.core.Relation;

import com.uni.framework.crud.base.dto.BaseResponseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 *  CmsArticle generated by auto
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-08-26.
 */
@Data
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = false)
@Relation(collectionRelation = "resources")
public class CmsArticleResponseDto extends BaseResponseDto {

    /**
     *
     */
    private static final long serialVersionUID = -1L;

    /**
     * TODO 字段信息描述
     */
    private String categoryId;

    /**
     * TODO 字段信息描述
     */
    private String articleId;

    /**
     * TODO 字段信息描述
     */
    private String groupId;

    /**
     * TODO 字段信息描述
     */
    private String accountId;

    /**
     * TODO 字段信息描述
     */
    private String groupName;

    /**
     * TODO 字段信息描述
     */
    private String accountName;

    /**
     * TODO 字段信息描述
     */
    private String title;

    /**
     * TODO 字段信息描述
     */
    private String summary;

    /**
     * TODO 字段信息描述
     */
    private String content;

    /**
     * TODO 字段信息描述
     */
    private String descr;

    /**
     * TODO 字段信息描述
     */
    private String href;

    /**
     * TODO 字段信息描述
     */
    private String pubtime;

    /**
     * TODO 字段信息描述
     */
    private Integer state;

    /**
     * TODO 字段信息描述
     */
    private String createTime;

}
