package com.uni.service.use.dto.request;

import com.uni.framework.crud.base.dto.BaseRequestDto;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import java.time.LocalDateTime;

/**
 *  UseRorg Dto generated by auto
 * 这是类的注释
 *
 * @author lait
 * Created On 2020-08-26.
 */
@Data
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = false)
public class UseRorgRequestDto extends BaseRequestDto {

    /**
     *
     */
    private static final long serialVersionUID = -1L;

    /**
     * TODO 字段信息描述
     */
    private String uid;

    /**
     * TODO 字段信息描述
     */
    private String groupid;

    /**
     * TODO 字段信息描述
     */
    private String postid;

    /**
     * TODO 字段信息描述
     */
    private String groupname;

    /**
     * TODO 字段信息描述
     */
    private String postname;

    /**
     * TODO 字段信息描述
     */
    private String appid;

    /**
     * TODO 字段信息描述
     */
    private String tenantid;

    /**
     * TODO 字段信息描述
     */
    private Integer isactive;

    /**
     * TODO 字段信息描述
     */
    private String createdby;

    /**
     * TODO 字段信息描述
     */
    private LocalDateTime createddate;

}
